### ISSUE TITLE
Version 1.0.0 sources

### ISSUE THREAD

**Issue by chicoxyzzy** [sindresorhus/symbol-observable#16]
Version 1.0.0 was published on npm https://www.npmjs.com/package/symbol-observable but there are no 1.0.0 version in repo. Could you update repo please to see what has changed?

**Comment by benlesh** [comment]
oops missed the tag. Thanks

**Comment by benlesh** [comment]
@chicoxyzzy, you can find 1.0.0 [here now](https://github.com/blesh/symbol-observable/tree/1.0.0)

Thanks for pointing that out.

**Comment by SamVerschueren** [comment]
Odd that is wasn't pushed to master first :p.

**Comment by jamestalmage** [comment]
@blesh 
FYI - tools like `np` and `cut-release` can help guard against common publishing errors..
