### ISSUE TITLE
1.0.3 breaks in environments without module

### ISSUE THREAD

**Issue by Rich-Harris** [sindresorhus/symbol-observable#24]
Hi – my app (which uses `most`, which depends on `symbol-observable`) is breaking after the release of 1.0.3, apparently due to https://github.com/blesh/symbol-observable/pull/23. https://github.com/blesh/symbol-observable/pull/23/commits/1750d26b2c545ebc8698064bde5987820a40f81e assumes that `module` exists, which is only true in Node or Node-like environments.

Let me know if you're interested in a PR that puts the `module` reference behind a `typeof`.

**Comment by benlesh** [comment]
Oops. I missed that in my review. Thank you.

**Comment by btd** [comment]
@blesh could you please publish this to npm?

**Comment by benlesh** [comment]
@btd done in 1.0.4. Sorry for the delay.
