### ISSUE TITLE
index.js in npm package missmatch

### ISSUE THREAD

**Issue by duydao** [sindresorhus/symbol-observable#26]
Hi

the file es/index.js in the npm package (https://registry.npmjs.org/symbol-observable/-/symbol-observable-1.0.3.tgz) seems to be different the one in this repository. This leads to an error in rollup (module cannot be found). Any chance that you could sync the npm package?

Thanks

**Comment by benlesh** [comment]
v 1.0.4 has been published. @duydao, can you confirm this fixes your issue and close if it does?

**Comment by duydao** [comment]
Great work, thanks alot!

**Comment by benlesh** [comment]
No problem. Sorry for the delay in getting that published
