### ISSUE TITLE
Add Symbol.observable to index.d.ts

### ISSUE THREAD

**Issue by appsforartists** [sindresorhus/symbol-observable#27]
I can't figure out the syntax.  Based on [lib.es2015.symbol.wellknown.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es2015.symbol.wellknown.d.ts), it's something like this:

```typescript
export interface SymbolConstructor {
  readonly observable: symbol;
}

export interface Symbol {
  readonly [Symbol.observable]: symbol;
}
```

@mhegazy, please help.

**Comment by appsforartists** [comment]
Looks like you've already attempted this: https://github.com/Microsoft/TypeScript/issues/8099

Can we please get it added to this library? :)

**Comment by mhegazy** [comment]
Modules have their own scope. so the interface `SymbolConstructor` is your local interface, and not the global one. use `declare global` to augment the global scope one.

```ts
declare global {
  export interface SymbolConstructor {
    readonly observable: symbol;
  }
  export interface Symbol {
    readonly[Symbol.observable]: symbol;
  }
}
```

**Comment by appsforartists** [comment]
Thanks.
