### ISSUE TITLE
Why is it a ponyfill?

### ISSUE THREAD

**Issue by ivstas** [sindresorhus/symbol-observable#37]
Hi!
According to the code in `/es/ponyfill.js`, there is a case when global env is being patched:
https://github.com/benlesh/symbol-observable/blob/c849a832223648ec703e4c93c74b7232a23f43b2/es/ponyfill.js#L10

If global env is patched, why is it called a ponyfill?

**Comment by SamVerschueren** [comment]
@ivstas Why did you close this? I have the exact same question. It shouldn't patch `Symbol.observable` imo.

**Comment by ivstas** [comment]
@SamVerschueren I created another issue which is relative to this one (https://github.com/benlesh/symbol-observable/issues/38)
