### ISSUE TITLE
Types don't use `unique symbol` type

### ISSUE THREAD

**Issue by pittst3r** [sindresorhus/symbol-observable#41]
Consumers of this library may do something like this:

```ts
import $$observable from 'symbol-observable';

export class Foo {
  [$$observable]() {
    return this;
  }
}
```

If using TypeScript their output .d.ts will look like the following, because `$$observable` is not a `unique symbol`:

```ts
export declare class Foo {
}
```

However, if we use the `unique symbol` type the output .d.ts will be:

```ts
import $$observable from 'symbol-observable';
export declare class Foo {
   [$$observable](): this;
}
```

This ~allows~ improves interop between observable interfaces with regards to typing (rxjs and xstream in my case). There are unfortunately more issues between rxjs and xstream; namely the `Subscribable` interfaces.

Would you accept a PR amending the types to use the `unique symbol` type? Note that using `unique symbol` would require a TS upgrade to [`~2.7.0`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#unique-symbol) and an update to rxjs so as to not regress https://github.com/ReactiveX/rxjs/issues/3697.

**Comment by benlesh** [comment]
This apparently is also at odds with `@types/node`, so we can't really make this fix until it's either fixed or removed there.

**Comment by benlesh** [comment]
Also of note: `symbol-observable@3.0.0` is updated to publish types for `Symbol.observable` as being `unique symbol` as well.

**Comment by skipjack** [comment]
I'm still seeing this issue with `symbol-observable@3.0.0` and `@types/node@14.14.35`...

``` bash
Error: node_modules/symbol-observable/index.d.ts:6:14 - error TS2717: Subsequent property declarations must have the same type.  Property 'observable' must be of type 'symbol', but here has type 'unique symbol'.

6     readonly observable: unique symbol;
               ~~~~~~~~~~

  node_modules/@types/node/globals.d.ts:146:14
    146     readonly observable: symbol;
                     ~~~~~~~~~~
    'observable' was also declared here.
```

__Update:__ Installing an older 2.x version of this package as noted in apollographql/apollo-client#7337 fixed the issue, still unsure why the latest of both wouldn't work though. Lmk if you'd like me to create a separate issue.
